name: cdfw CI

on: [push, pull_request]

env:
  pio_env: macos
  os: macos

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: platformio-${{ env.os }}
    - name: Setup SDL2 frameworks
      uses: BrettDong/setup-sdl2-frameworks@main
      with:
        sdl2: latest
    - name: Build firmware for env ${{ env.pio_env }} on ${{ env.os }}
      run: pio run -e ${{ env.pio_env }}
