name: cdfw CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  pio_env: macos-cov
  os: macos

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: platformio-${{ env.os }}
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install SDL2 frameworks
      run: brew install sdl2
    - name: Build firmware for env ${{ env.pio_env }} on ${{ env.os }}
      run: pio run -e ${{ env.pio_env }}

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: platformio-${{ env.os }}
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install SDL2 frameworks
      run: brew install sdl2
    - name: Install LLVM
      run: brew install llvm
    - name: Run tests for env ${{ env.pio_env }} on ${{ env.os }}
      run: pio test -e ${{ env.pio_env }}
    - name: Generate coverage report
      run: ./tools/gen-cov.sh
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage/cdfw.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
